# Generated by Django 3.1.3 on 2020-11-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todod',
            new_name='Todo',
        ),
    ]
