# Generated by Django 3.1.3 on 2020-11-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20201103_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descriptin',
            new_name='description',
        ),
    ]
